language: python

os:
  - linux

python:
  - 3.6
  - 3.6-dev
  - 3.7-dev

cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


install:
  - pip install virtualenv --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .

script:
  - coverage run -m pytest --cov=gdax

notifications:
  email: false
